services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=notedb
    ports:
      - "5432:5432"
    command: ["postgres", "-c", "log_statement=all"]

  redis:
    image: redis:latest

  app:
    build: .
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/notedb
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
